### ISSUE TITLE
新版文件目录@Each.VideoFiles不显示未识别的文件

### ISSUE THREAD

**Issue by Nchyn** [kaedei/dandanplay-libraryindex#11]
新版文件目录@Each.VideoFiles不显示未识别的文件，如标题，会在首位有一个空白字段生成，后跟逗号“,”
![image](https://user-images.githubusercontent.com/28627461/48628819-0f6e1f00-e9f3-11e8-8a48-15781de91a0d.png)

**Comment by kaedei** [comment]
这是远程访问服务器端的问题，已经在PC端9.0版中修复了。
在首页中，episodeId=0的视频，动画标题将显示为“未识别”，剧集标题为空。
在播放页面中，episodeId=0的视频，动画标题将显示为“未识别”，剧集标题为文件名。
