### ISSUE TITLE
大佬你好！前来请求2件事情。

### ISSUE THREAD

**Issue by mqdlzh** [kaedei/dandanplay-libraryindex#16]
1.关于Dplayer只身外挂.vtt web字幕的问题，是不是因为nancyfx文件用Hash访问所以没法找到真实字幕文件路径所以没法加载？（其实在一些用Nginx的Dplayer播放器也是挂载不了，但我有见到过成功的，也不是很清楚怎么弄的）

2.能否添加上视频连播的功能，或者提示跳转下一P，而不是要切回前一个页面去找下一个视频。

本人不懂web编写，也不懂HTML5中关于HLS什么的特性，只是百度现学现卖，如有错误还请指出。

最后感谢弹弹Play为众多肥·宅做的贡献。

**Comment by wujx3433** [comment]
同求。我缓存的一些动画是外挂字幕，而且动画本体是无字幕的。
![image](https://user-images.githubusercontent.com/32533580/56878370-5b36f100-6a86-11e9-911b-b9068f4e6bdf.png)
![image](https://user-images.githubusercontent.com/32533580/56878396-7c97dd00-6a86-11e9-94fe-7b9b279cc7b6.png)
虽然不是听不懂，不过还是带字幕舒服点。
至于MKV内置字幕的情况，也不能加载。

另，H.265视频貌似支持的不好，如图：
![image](https://user-images.githubusercontent.com/32533580/56878628-9e459400-6a87-11e9-9d3e-7fc9884a428f.png)
![image](https://user-images.githubusercontent.com/32533580/56878655-c03f1680-6a87-11e9-8242-835fac3aac22.png)

**Comment by kaedei** [comment]
之前没考虑过支持vtt字幕……你是指本地已经有vtt格式的字幕文件，希望播放时能加载出来吗？这个应该问题不大。

连播功能，可能在页面上放个“上一集”、“下一集”的链接会比较省事吧。

**Comment by mqdlzh** [comment]
> 之前没考虑过支持vtt字幕……你是指本地已经有vtt格式的字幕文件，希望播放时能加载出来吗？这个应该问题不大。
> 
> 连播功能，可能在页面上放个“上一集”、“下一集”的链接会比较省事吧。

1.关于.vtt确实就是想挂本地的文件，之前就在代码里看到相关功能，同时也查询过Dplayer的代码使用，只是不太了解nancyfx下的Hash文件名称使用，所以就算是开启了字幕功能也是显示不了字幕。（之前用过可道云，可道云里的Dplayer插件提供了vtt字幕加载功能所以就照抄过去了，貌似没有任何作用）
![20190502225913](https://user-images.githubusercontent.com/31967654/57085421-bb4fc080-6d2e-11e9-87ca-36e8a4102bb9.png)

2.添加一个下一集或上一集的按钮就好了，连播功能估计要写挺多代码的，也不太好意思麻烦大佬了。

3.关于视频库web页面优化的问题。就是添加的视频数量一多首页就会变得超级长。。。
![20190502225829](https://user-images.githubusercontent.com/31967654/57085681-4df05f80-6d2f-11e9-991d-0ecd5bf30ee6.png)
像这样首页不显示单个的视频，直接就是显示个作品列表，不再显示单个视频。
![20190502225731](https://user-images.githubusercontent.com/31967654/57085690-5183e680-6d2f-11e9-9783-543982e27f3d.png)
这是我在代码里做出的修改。。。实在是不懂怎么用。外行人。。。。

下面的话大佬嫌麻烦可以不用理睬的。

如果可能，是否可以把列表显示方式修改为像弹弹play软件那样的带封面图片的（带评分什么的就算了，虽然想这样弄）。
![20190502231709](https://user-images.githubusercontent.com/31967654/57086310-73319d80-6d30-11e9-9db9-505368628b80.png)

同时添加个左侧滑出栏同时按番剧上映时间分类的选项，方便查找。

**Comment by kaedei** [comment]
新的测试版 9.4.6.509 中远程访问功能改进了这个issue中提到的相关内容：

- 首页样式更新：每行会最多显示3个视频，移除了一些文字让每个格子更紧凑。
- 支持自定义web首页的相关内容（网页最上方的网站名称、关于链接等）。
- 支持隐藏web首页的视频列表区域（有过滤条件时仍然会显示视频列表）。
- 播放页中，播放器下方会显示当前动画的剧集列表，方便进行跳转。
- 播放页支持自动加载vtt字幕文件（vtt文件需要和视频同目录同名），例如播放 `a.mp4` 时可以加载 `a.vtt` 或 `a.mp4.vtt` （**还没有测试过**）
- “远程访问”页面的设置会在修改后实时自动保存（web验证、个性化设置、API秘钥等），无法自动保存的在旁边有文字说明
- 增加根据视频文件id访问文件流、弹幕等API接口
- url中使用文件id代替Hash，解决了相同Hash存在多份相同视频的选择问题。例如由以前的 `/web/0000FFFF` 变成了 `/web/0000-0000-1111-2222`
- 修复了可能会出现重复弹幕的问题

**Comment by mqdlzh** [comment]
好的，非常感谢，这就去测试！！！

**Comment by mqdlzh** [comment]
测试完毕了，辛苦大佬了。关于vtt字幕文件，Dplayer已经有显示加载vtt字幕的记录但貌似没法找到文件？
![301](https://user-images.githubusercontent.com/31967654/57566308-7f3af080-73fd-11e9-808c-86a8f24c410e.png)
这是在chrome开发工具里看见对的记录
![302](https://user-images.githubusercontent.com/31967654/57566320-ae516200-73fd-11e9-9da6-fb27752384ef.png)
确定视频文件和字幕文件在同一个文件夹内，且文件名相同（甚至为了防止文件名过长精简了，同时放置在根目录）
![303](https://user-images.githubusercontent.com/31967654/57566342-dd67d380-73fd-11e9-8b1e-1973a9ed1cb4.png)
![304](https://user-images.githubusercontent.com/31967654/57566344-e5c00e80-73fd-11e9-9dcf-df0624b47303.png)
视频和字幕文件都是确认没问题的。

顺带说一个奇怪的事情：在chrome下Dplayer的按钮显示语言是英文的。但在Edge下却又是中文的。。。emmm....
![001](https://user-images.githubusercontent.com/31967654/57566357-215ad880-73fe-11e9-923d-54e1cf001724.png)
![002](https://user-images.githubusercontent.com/31967654/57566360-2750b980-73fe-11e9-890c-12f1ab645741.png)
chrome支持HTML5 的webm特性，mkv文件可以直接播放。
![101](https://user-images.githubusercontent.com/31967654/57566371-40f20100-73fe-11e9-899a-cc0be3a7e4f4.png)
![102](https://user-images.githubusercontent.com/31967654/57566373-48b1a580-73fe-11e9-9b52-e91f9eef4269.png)
Edge旧版不支持webm。。。视频加载失败（新版Edge听说挺好的，大佬有兴趣可以去了解一下）

![401](https://user-images.githubusercontent.com/31967654/57566492-c2965e80-73ff-11e9-8b9c-5ad94131ada6.png)
顺带一提，我发现了一款可以在线挂载ass字幕的云盘（但要开超级会员才能用），和百度云的字幕不同，它是支持自动挂载云盘同文件夹下的字幕文件。（虽然挂的是ass字幕，但显示效果和SRT字幕是一样的。。。）

**Comment by mqdlzh** [comment]
哦，忘记说了，测试页面 ipv6.mashiro334.cn 这是借弹弹play远程访问弄的一个网站。（是的只支持ipv6访问。。。）实在不行可以改 ipv4.mashiro334.cn(电信锁80端口改端口了。。。)

**Comment by kaedei** [comment]
vtt的问题我再测试一下。
至于DPlayer的功能缺失问题，还有播放某些格式视频时有问题，或者是无法加载ass字幕，这些目前都是无能为力的，没有办法解决。

**Comment by mqdlzh** [comment]
好的，只要可以挂vtt就很感谢了！
