### ISSUE TITLE
关于.flv文件的问题

### ISSUE THREAD

**Issue by zhegexiankabutaileng** [kaedei/dandanplay-libraryindex#17]
您好，有以下两个问题：
1.发现远程播放无法播放.flv文件，在查阅Dplayer的文档后，在vedio.html里加入了flv.js，但是发现还是没有办法播放。在线播放器的属性里写的type: norml。
后来在type那个属性的位置吧'auto'改成'.flv'就可以播放flv文件了。但是其他文件又无法正常播放了。
2.请问是否有办法访问到当前文件的后缀名使得能够把auto改成后缀

**Comment by kaedei** [comment]
感谢反馈，我先研究一下

**Comment by zhegexiankabutaileng** [comment]
> 感谢反馈，我先研究一下

emmm刚刚看了看dandanplay的文档，实现了读取后缀名......

```
var fileName = '' ;
@Each.VideoFiles
    @If.IsCurrent
	fileName = '@Current.FileName';
    @EndIf
@EndEach
var fileExtension = fileName.split('.').pop().toLowerCase() ;
```

```
video: {
	url: '@Model.Video',
	pic: '@Model.Image',
	//type: 'auto'
	type: fileExtension
},
```

这样可以播放flv了。怀疑原因是url传入的是Hash值不带有后缀，使得auto无法识别格式

**Comment by kaedei** [comment]
这个问题之前通过url后面带上文件扩展名的方式已经解决了，现在可以关掉
