### ISSUE TITLE
希望增加按文件夹查看

### ISSUE THREAD

**Issue by zxloveyyy** [kaedei/dandanplay-libraryindex#19]
视频数量多了后,密密麻麻根本分不清

**Comment by kaedei** [comment]
文件夹也是一种管理方式。
这个将来会做的……后台接口需要先升级一下，然后改下界面。

**Comment by xiaomujin** [comment]
> 文件夹也是一种管理方式。 这个将来会做的……后台接口需要先升级一下，然后改下界面。

2年了=-=

**Comment by JasonYuchen** [comment]
四年了，是希望这样使用的人太少了吗哭😢
