### ISSUE TITLE
mkv/视频 无法播放

### ISSUE THREAD

**Issue by V-Conet** [kaedei/dandanplay-libraryindex#21]
几乎所有视频文件都为多轨mkv文件,文件大小多为1G左右,但无法播放
![](https://gitee.com/vconet/img-repo/raw/master/image/Snipaste_2020-05-27_16-00-19.png)
字幕加载为404
![](https://gitee.com/vconet/img-repo/raw/master/image/Snipaste_2020-05-27_16-01-24.png)

**Comment by kaedei** [comment]
在浏览器中播放时是浏览器本身负责解码，目前大部分浏览器都还不支持mkv格式，建议换用mp4格式的视频。
浏览器中目前只支持vtt格式的外挂字幕，不支持srt/ass格式的外挂字幕，也不支持视频内嵌字幕。
