### ISSUE TITLE
希望可以在linux服务器上面使用

### ISSUE THREAD

**Issue by CberYellowstone** [kaedei/dandanplay-libraryindex#23]
想在我的NAS上面部署,是centos系统,
毕竟想在手机看番时还要开电脑就有点....多此一举?
所以请问能不能把远程访问功能单独整理成为一个软件包?

**Comment by CberYellowstone** [comment]
@stu43005 @kaedei @kansaer @Nchyn

**Comment by kansaer** [comment]
linux在code中。。。。（咕咕咕）

**Comment by CberYellowstone** [comment]
> linux 在 code 中。。。。（咕咕咕）

linux上我觉得可以把这个功能单独提出来
开发者辛苦了,等待linux版的到来

**Comment by kaedei** [comment]
现在播放器中的代码不支持直接拿过来跑在Linux上。Web部分还好说，就是媒体库和收录视频的部分移植起来比较麻烦，比如解析匹配视频、生成缩略图等都要重写。

目前没有什么动力去开新的项目了，不确定有多少人需要这个东西。毕竟像emby之类的软件都已经很成熟了。

不过好在全部API都有，有兴趣可以去自己实现一个。

**Comment by CberYellowstone** [comment]
> 现在播放器中的代码不支持直接拿过来跑在 Linux 上。Web 部分还好说，就是媒体库和收录视频的部分移植起来比较麻烦，比如解析匹配视频、生成缩略图等都要重写。
> 
> 目前没有什么动力去开新的项目了，不确定有多少人需要这个东西。毕竟像 emby 之类的软件都已经很成熟了。
> 
> 不过好在全部 API 都有，有兴趣可以去自己实现一个。

主要是emby之类的貌似没有弹幕功能
我想在linux上除了web部分使用的人可能真的会很少哦
毕竟把linux当成日用的人应该没有把linux当成生产系统的人多

**Comment by kaedei** [comment]
> > 现在播放器中的代码不支持直接拿过来跑在 Linux 上。Web 部分还好说，就是媒体库和收录视频的部分移植起来比较麻烦，比如解析匹配视频、生成缩略图等都要重写。
> > 目前没有什么动力去开新的项目了，不确定有多少人需要这个东西。毕竟像 emby 之类的软件都已经很成熟了。
> > 不过好在全部 API 都有，有兴趣可以去自己实现一个。
> 
> 主要是emby之类的貌似没有弹幕功能
> 我想在linux上除了web部分使用的人可能真的会很少哦
> 毕竟把linux当成日用的人应该没有把linux当成生产系统的人多

web只是个界面，后台服务是不可缺少的。界面上媒体库的数据需要一个后台服务来收集，比如要监视文件夹中的变化，解析视频，下载弹幕等等。如果要移植Linux，这些都是必须要做的。

**Comment by CberYellowstone** [comment]
> > > 现在播放器中的代码不支持直接拿过来跑在 Linux 上。Web 部分还好说，就是媒体库和收录视频的部分移植起来比较麻烦，比如解析匹配视频、生成缩略图等都要重写。
> > > 目前没有什么动力去开新的项目了，不确定有多少人需要这个东西。毕竟像 emby 之类的软件都已经很成熟了。
> > > 不过好在全部 API 都有，有兴趣可以去自己实现一个。
> > 
> > 
> > 主要是 emby 之类的貌似没有弹幕功能
> > 我想在 linux 上除了 web 部分使用的人可能真的会很少哦
> > 毕竟把 linux 当成日用的人应该没有把 linux 当成生产系统的人多
> 
> web 只是个界面，后台服务是不可缺少的。界面上媒体库的数据需要一个后台服务来收集，比如要监视文件夹中的变化，解析视频，下载弹幕等等。如果要移植 Linux，这些都是必须要做的。

我现在正在试着用php重写部分内容,主要思路大致有了,现在看看能不能实现

**Comment by qmzmdqs** [comment]
其实这个软件搜索、缓存国内几大视频网站弹幕的功能很好用，我是为了这个功能而用的。而且我基本是用网页版播放，因为不知道什么原因，我用客户端版经常卡。。有些操作要响应一会

**Comment by CberYellowstone** [comment]
完成了！ [测试版](https://github.com/CberYellowstone/DanDanPlay-PHP)

**Comment by kaedei** [comment]
感谢，我更新下readme

**Comment by CberYellowstone** [comment]
> 感谢，我更新下 readme

刚准备写新的issue呢,在这里顺便说了吧:

api.acplay.net的弹幕api能否增加一个通过episodeId获取与远程访问一致格式的弹幕?
通过api获取的弹幕与dplayer所需的格式不同,很难重解析, 要是api提供的弹幕格式能直接用就好了
(dplayer的弹幕格式与安卓版的弹幕格式好像一致)

**Comment by CberYellowstone** [comment]
> 感谢，我更新下 readme

现在就导致有的番能重构弹幕有的不行, 就导致了有的番剧的弹幕会报错, 
而且毫无头绪报错在于哪
肉眼分辨的弹幕格式明明是一样的 orz

**Comment by kaedei** [comment]
> > 感谢，我更新下 readme
> 
> 刚准备写新的issue呢,在这里顺便说了吧:
> 
> api.acplay.net的弹幕api能否增加一个通过episodeId获取与远程访问一致格式的弹幕?
> 通过api获取的弹幕与dplayer所需的格式不同,很难重解析, 要是api提供的弹幕格式能直接用就好了
> (dplayer的弹幕格式与安卓版的弹幕格式好像一致)

dplayer、弹弹play、BiliBili这三者的弹幕文件格式都是不同的，没办法用同一段逻辑去加载。
dplayer格式是 [[time,mode,color,userID,text]]
弹弹play api格式是 {cid:cid, p:"time,mode,color,userID", m: text}
BiliBili格式是 <d p="time,mode,size,color,ts,pool,userID,id">text</d>

弹幕报错问题应该和这些无关。如果还有问题的话可以单独开个issue贴上细节信息。

**Comment by CberYellowstone** [comment]
> > > 感谢，我更新下 readme
> > 
> > 
> > 刚准备写新的 issue 呢，在这里顺便说了吧:
> > api.acplay.net 的弹幕 api 能否增加一个通过 episodeId 获取与远程访问一致格式的弹幕？
> > 通过 api 获取的弹幕与 dplayer 所需的格式不同，很难重解析，要是 api 提供的弹幕格式能直接用就好了
> > (dplayer 的弹幕格式与安卓版的弹幕格式好像一致)
> 
> dplayer、弹弹 play、BiliBili 这三者的弹幕文件格式都是不同的，没办法用同一段逻辑去加载。
> dplayer 格式是 [[time,mode,color,userID,text]]
> 弹弹 play api 格式是 {cid:cid, p:"time,mode,color,userID", m: text}
> BiliBili 格式是 `<d p="time,mode,size,color,ts,pool,userID,id">text</d>`
> 
> 弹幕报错问题应该和这些无关。如果还有问题的话可以单独开个 issue 贴上细节信息。

感谢大佬指教
我灵感一来把和这个bug修好了!
