### ISSUE TITLE
如何让客户端可以判断节点可用性

### ISSUE THREAD

**Issue by kkbllt** [kaedei/dandanplay-libraryindex#36]
在使用了大佬编写好的python项目 (https://pastebin.ubuntu.com/p/b33zZ3pvVr/) 成功部署后，
客户端点击测试节点是否可用时会发送一个/list?r=<random_int>的请求，那么服务端要返回什么信息才能让客户端判断为可用节点？

**Comment by kaedei** [comment]
在原有的官方节点里，访问不带查询参数的 `/list` 接口将会返回最新的200条资源。
不过为了回应客户端的测试，只要返回的json符合格式要求就可以了（执行了搜索但结果为空）。甚至可以直接返回一个空的json对象 `{}`

**Comment by kkbllt** [comment]
非常感谢，我之后有空研究一下
