### ISSUE TITLE
[Bug] 无法访问远程媒体库的视频缩略图

### ISSUE THREAD

**Issue by Sanlorng** [kaedei/dandanplay-libraryindex#39]
**版本**： 弹弹Play 12.3.1 (UWP)
**描述**：在手机端使用弹弹Play概念版时，发现缩略图不能正常加载，于是尝试打开网页版媒体库，但缩略图也不能正常显示。查看了API 文档后，自己在浏览器地址拼接 `image url` 并得到如下结果(测试使用的数据其LastThumbnail 不为空)

1. 使用 `/api/v1/image/{hash}` API

- 使用 hash 拼接 (http://localhost/api/v1/image/E511CEE956500B4C74EA1E2DA8D5EB24): 提示 404 not found
- 使用 id 拼接 (http://localhost/api/v1/image/4a22615a-4cd4-4223-a626-59a8f104d442): 显示一个图片，但是是弹弹Play的图标

2. 使用 `/api/v1/image/{id}` API
- 使用 hash 拼接 (http://localhost/api/v1/image/id/E511CEE956500B4C74EA1E2DA8D5EB24): 提示 500 内部服务器错误
- 使用 id 拼接 (http://localhost/api/v1/image/id/4a22615a-4cd4-4223-a626-59a8f104d442): 提示 404 not found

**预期行为**:

- 使用 hash 拼接 `/api/v1/image/{hash}` (http://localhost/api/v1/image/E511CEE956500B4C74EA1E2DA8D5EB24) 能够正常显示缩略图
- 使用 id 拼接  `/api/v1/image/id/{id}`  (http://localhost/api/v1/image/id/4a22615a-4cd4-4223-a626-59a8f104d442) 能够正常显示缩略图

**Comment by kaedei** [comment]
`E511CEE956500B4C74EA1E2DA8D5EB24`应该是hash，`4a22615a-4cd4-4223-a626-59a8f104d442`是id。

缩略图无法显示是很常见的事情，例如缩略图尚未生成（在队列中）、图片损坏，或是媒体文件正被占用、已经移除、无法快速渲染（部分HEVC视频）等众多情况都会影响缩略图生成。所以此时访问接口同样也拿不到图片。

遇到这种情况可以在PC客户端-媒体库-右键点击媒体文件，选择”重设视频缩略图“，下次刷新媒体库时会尝试刷新缩略图。

如果要写客户端，要做好接口可能返回失败的处理。

**Comment by Sanlorng** [comment]
> `E511CEE956500B4C74EA1E2DA8D5EB24`应该是hash，`4a22615a-4cd4-4223-a626-59a8f104d442`是id。
> 
> 缩略图无法显示是很常见的事情，例如缩略图尚未生成（在队列中）、图片损坏，或是媒体文件正被占用、已经移除、无法快速渲染（部分HEVC视频）等众多情况都会影响缩略图生成。所以此时访问接口同样也拿不到图片。
> 
> 遇到这种情况可以在PC客户端-媒体库-右键点击媒体文件，选择”重设视频缩略图“，下次刷新媒体库时会尝试刷新缩略图。
> 
> 如果要写客户端，要做好接口可能返回失败的处理。
> 

是全部缩略图都不显示……我只是拿其中一个进行测试，在弹弹Play PC端里，它们都是有缩略图的

**Comment by kaedei** [comment]
之前的版本已经修复此问题

**Comment by Sanlorng** [comment]
> 之前的版本已经修复此问题

测试了一下，PC版是正常的，UWP依然有这个问题
