### ISSUE TITLE
远程访问 不能跳转进度。

### ISSUE THREAD

**Issue by ScalaFirst** [kaedei/dandanplay-libraryindex#55]
我是用nginx转发的服务端口，转发后就不能跳转进度了，但是使用端口还是可以跳转的

**Comment by kaedei** [comment]
这个就不太熟悉了，跳转进度应该依靠http header里面的 Range，可能是nginx处理时有什么不一样。
比如 proxy_force_ranges 之类的没加上？

**Comment by ScalaFirst** [comment]
改成直接端口访问了，用反向代理确实没法跳进度

Kaedei ***@***.***> 于2023年5月23日周二 18:53写道：
