### ISSUE TITLE
HEVC编码的视频出现"视频加载失败"

### ISSUE THREAD

**Issue by Leo79-code** [kaedei/dandanplay-libraryindex#56]
Win端：
Windows 11 专业版 22H2
使用无线网卡Realtek RTL8852AE WiFi 6 802.11ax PCIe Adapter的移动热点功能

移动端：
iPhone 13 Pro iOS 16.5 连接到上述电脑端移动热点，Safari浏览器

HEVC, x265的视频文件都无法正常播放，x264的可以正常加载

**Comment by kaedei** [comment]
目前网页端播放用的是<video>标签，也就是依靠浏览器自身的解码。如hevc编码、mkv格式等等，浏览器不支持的话是播放不出来的。
可能需要加入后台转码才能解决

**Comment by Leo79-code** [comment]
https://github.com/DIYgod/DPlayer/issues/729
https://github.com/DIYgod/DPlayer/issues/434
搜了一下 好像是Safari上的DPlayer就不支持特殊格式:(

**Comment by kaedei** [comment]
如果经常用远程访问功能，平时下载时请尽量选择H264 mp4的资源。

弹弹之后会考虑加个转码的功能，可以闲时给特定格式的视频转码成浏览器支持的格式
