### ISSUE TITLE
弹弹play开放平台文档的链接打不开

### ISSUE THREAD

**Issue by Xinyu-Li-123** [kaedei/dandanplay-libraryindex#59]
[api/OpenPlatform.md](https://github.com/kaedei/dandanplay-libraryindex/blob/2ef06d0fdd0ebf58ec254205835eedf5990d3f8e/api/OpenPlatform.md#%E5%BC%B9%E5%BC%B9play%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E4%BB%8B%E7%BB%8D)里提供的弹弹play开放平台文档的链接打不开来，这个文件里提供的链接是[https://api.acplay.net/swagger](https://api.acplay.net/swagger) 。我认为可能是由于域名修改过了，因为我在[https://api.dandanplay.net/swagger/](https://api.dandanplay.net/swagger/)里看到了类似文档的页面。

**Comment by kaedei** [comment]
是的，dandanplay.net 是当前使用的域名。文档已更新 16dbe33bb82eb4b9801836abcc8239c493bddbf4
